# Site Settings
baseurl: ""
url : "https://shanmuga.sudan.github.io"

# Blog Settings
theme_settings :
  title : Shanmuga's Blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/Shanmuga.jpg
    username : Shanmuga Sudan Veerabahu
    description : Software Developer with a passion for building clean, maintainable software products that simplifies end-user experience at the same time achieve desired results
    education :
      - start : July 2009
        end   : May  2013
        major : B.Tech in Electrical and Electronics Engineering
      - start : January  2016
        end   : December 2017
        major : M.S in Information Systems
    certifications :
      - start : August 2020
        end   : August 2023
        major : AWS Certified Solutions Architect - Associate (SAA - C02)
    experience :
      - start : July   2013
        end : December 2015
        experience : Tata Consultancy Services, Chennai, India
      - start : March 2018
        end : January 2020
        experience  : JDA Software Group, Inc., Boston, USA
      - start : April 2020
        end   : May   2020
        experience  : Vestmark, Inc., Boston, USA 
    skills : 
      - skill : Java
        value : 70  # Percent value
      - skill : JavaScript
        value : 50  # Percent value
      - skill : C++
        value : 40  # Percent value
      - skill : HTML 5
        value : 70  # Percent value
      - skill : CSS 3
        value : 40  # Percent value
      - skill : Bootstrap
        value : 40  # Percent value
      - skill : Spring Framework
        value : 50  # Percent value
      - skill : Hibernate ORM
        value : 50  # Percent value
      - skill : SQL
        value : 60  # Percent value
      - skill : AWS Services
        value : 40  # Percent value

  # Icons
  icons :
    email:  "veerabahu.sh@northeastern.edu"
    linkedin:  https://www.linkedin.com/in/shanmuga-sudan 
    github: https://github.com/shanmuga-sudan
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
plugins: [jekyll-paginate]
bootstrap:
  assets: true
